spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/rent
animal:
  disable: "panda"
management:
  endpoints:
    web:
      exposure:
        include: "*"