spring:
  application:
    name: rent-fare
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/rent
server:
  port: 9004

management:
  endpoints:
    web:
      exposure:
        include: "*"

base:
  currency: "RUB"